"""File storage abstraction.

Application code depends on the ``Storage`` protocol only. ``LocalStorage`` (a directory on
disk / a Docker volume) is implemented; an S3-compatible backend is a later phase and will
implement the same protocol, so nothing above this module changes.

Keys are validated strictly: they are *always* generated by the application from UUIDs and
constants, never from user input, and this module still refuses anything that could escape
the storage root.
"""

from __future__ import annotations

import contextlib
import hashlib
import os
import re
import shutil
import uuid
from collections.abc import Iterable, Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import BinaryIO, Protocol

MAX_KEY_LENGTH = 512
# Every path segment must start with a letter or digit, which excludes "", ".", ".." and
# hidden names, and only allows a conservative character set. No backslashes, no NULs.
_KEY_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*(?:/[A-Za-z0-9][A-Za-z0-9._-]*)*$")
_COPY_CHUNK = 1024 * 1024


class StorageError(Exception):
    pass


class InvalidStorageKeyError(StorageError, ValueError):
    pass


class ObjectNotFoundError(StorageError, FileNotFoundError):
    pass


class ObjectTooLargeError(StorageError):
    pass


@dataclass(frozen=True)
class StoredObject:
    key: str
    size: int
    sha256: str


def validate_key(key: str) -> str:
    if not isinstance(key, str) or not key or len(key) > MAX_KEY_LENGTH:
        raise InvalidStorageKeyError("invalid storage key")
    if not _KEY_PATTERN.fullmatch(key):
        raise InvalidStorageKeyError("invalid storage key")
    return key


class Storage(Protocol):
    def put_bytes(self, key: str, data: bytes) -> StoredObject: ...

    def put_stream(
        self, key: str, chunks: Iterable[bytes], *, max_bytes: int | None = None
    ) -> StoredObject: ...

    def open(self, key: str) -> BinaryIO: ...

    def read_bytes(self, key: str) -> bytes: ...

    def exists(self, key: str) -> bool: ...

    def size(self, key: str) -> int: ...

    def delete(self, key: str) -> None: ...

    def delete_prefix(self, prefix: str) -> int: ...

    def local_copy(self, key: str) -> contextlib.AbstractContextManager[Path]: ...


class LocalStorage:
    """Stores objects as files under ``root``."""

    def __init__(self, root: Path | str) -> None:
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------ paths
    def _path(self, key: str) -> Path:
        validate_key(key)
        path = (self.root / key).resolve()
        if self.root not in path.parents:  # defence in depth against symlinks / odd inputs
            raise InvalidStorageKeyError("invalid storage key")
        return path

    # ------------------------------------------------------------------ writing
    def put_bytes(self, key: str, data: bytes) -> StoredObject:
        return self.put_stream(key, [data])

    def put_stream(
        self, key: str, chunks: Iterable[bytes], *, max_bytes: int | None = None
    ) -> StoredObject:
        """Write ``chunks`` atomically (temp file + rename), hashing as we go.

        Enforces ``max_bytes`` *while streaming* and removes the partial file on any
        failure, so an oversized or aborted upload never leaves debris behind.
        """
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        temp = path.with_name(f".{path.name}.{uuid.uuid4().hex}.part")
        digest = hashlib.sha256()
        size = 0
        try:
            with temp.open("wb") as handle:
                for chunk in chunks:
                    size += len(chunk)
                    if max_bytes is not None and size > max_bytes:
                        raise ObjectTooLargeError(f"object exceeds {max_bytes} bytes")
                    digest.update(chunk)
                    handle.write(chunk)
            os.replace(temp, path)
        except BaseException:
            temp.unlink(missing_ok=True)
            raise
        return StoredObject(key=key, size=size, sha256=digest.hexdigest())

    # ------------------------------------------------------------------ reading
    def open(self, key: str) -> BinaryIO:
        path = self._path(key)
        try:
            return path.open("rb")
        except FileNotFoundError as exc:
            raise ObjectNotFoundError(key) from exc

    def read_bytes(self, key: str) -> bytes:
        with self.open(key) as handle:
            return handle.read()

    def exists(self, key: str) -> bool:
        return self._path(key).is_file()

    def size(self, key: str) -> int:
        try:
            return self._path(key).stat().st_size
        except FileNotFoundError as exc:
            raise ObjectNotFoundError(key) from exc

    @contextmanager
    def local_copy(self, key: str) -> Iterator[Path]:
        """A real filesystem path for libraries that need one (read-only use)."""
        path = self._path(key)
        if not path.is_file():
            raise ObjectNotFoundError(key)
        yield path

    # ------------------------------------------------------------------ deleting
    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)

    def delete_prefix(self, prefix: str) -> int:
        """Remove everything under ``prefix`` (a "directory"). Returns files removed.

        A prefix is mandatory (never the storage root) and validated like any key.
        """
        directory = self._path(prefix)
        if not directory.is_dir():
            return 0
        removed = sum(1 for item in directory.rglob("*") if item.is_file())
        shutil.rmtree(directory, ignore_errors=True)
        return removed


@lru_cache
def get_storage() -> Storage:
    from app.core.config import get_settings  # imported lazily: keeps this module dependency-free

    settings = get_settings()
    if settings.storage_type == "local":
        return LocalStorage(settings.storage_local_root)
    raise StorageError("S3 storage is not implemented yet; use STORAGE_TYPE=local for now")
