"""Initial schema: users, catalogues, pipeline artefacts, candidates, products, audit.

Revision ID: 0001
Revises:
Create Date: 2026-09-20

Hand-written (not autogenerated) so the intent is explicit. The test-suite
(tests/test_migrations.py) fails if this file and the models ever drift apart.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBEDDING_DIM = 512  # frozen copy: migrations must not import mutable app constants


# --------------------------------------------------------------------------- helpers
def _id() -> sa.Column:
    return sa.Column(
        "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
    )


def _created_at() -> sa.Column:
    return sa.Column(
        "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
    )


def _updated_at() -> sa.Column:
    return sa.Column(
        "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
    )


def _pk(table: str) -> sa.PrimaryKeyConstraint:
    return sa.PrimaryKeyConstraint("id", name=op.f(f"pk_{table}"))


def _fk(
    table: str, column: str, ref_table: str, ondelete: str | None = None
) -> sa.ForeignKeyConstraint:
    return sa.ForeignKeyConstraint(
        [column],
        [f"{ref_table}.id"],
        name=op.f(f"fk_{table}_{column}_{ref_table}"),
        ondelete=ondelete,
    )


def _uq(table: str, *columns: str, name: str | None = None) -> sa.UniqueConstraint:
    return sa.UniqueConstraint(*columns, name=op.f(name or f"uq_{table}_{columns[0]}"))


def _ck(table: str, name: str, expression: str) -> sa.CheckConstraint:
    return sa.CheckConstraint(expression, name=op.f(f"ck_{table}_{name}"))


def _enum(name: str, default: str | None = None, nullable: bool = False) -> sa.Column:
    return sa.Column(
        name,
        sa.String(32),
        nullable=nullable,
        server_default=default,
    )


def _json(name: str, default: str) -> sa.Column:
    return sa.Column(
        name,
        postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        server_default=sa.text(f"'{default}'::jsonb"),
    )


def _bbox(nullable: bool) -> list[sa.Column]:
    return [sa.Column(f"bbox_{c}", sa.Float(), nullable=nullable) for c in ("x0", "y0", "x1", "y1")]


def _idx(table: str, *columns: str, name: str | None = None) -> None:
    op.create_index(op.f(name or f"ix_{table}_{columns[0]}"), table, list(columns))


# --------------------------------------------------------------------------- upgrade
def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ---- users
    op.create_table(
        "users",
        _id(),
        _created_at(),
        _updated_at(),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(255), nullable=True),
        _enum("role", "CUSTOMER"),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        _pk("users"),
        _uq("users", "email"),
    )

    # ---- suppliers
    op.create_table(
        "suppliers",
        _id(),
        _created_at(),
        _updated_at(),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("slug", sa.String(160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website", sa.String(512), nullable=True),
        sa.Column("contact_email", sa.String(320), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        _pk("suppliers"),
        _uq("suppliers", "name"),
        _uq("suppliers", "slug"),
    )

    # ---- categories (self-referencing tree)
    op.create_table(
        "categories",
        _id(),
        _created_at(),
        _updated_at(),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("slug", sa.String(160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        _pk("categories"),
        _fk("categories", "parent_id", "categories", ondelete="RESTRICT"),
        _uq("categories", "slug"),
    )
    _idx("categories", "parent_id")

    # ---- app_settings
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        _updated_at(),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_settings")),
        _fk("app_settings", "updated_by_id", "users", ondelete="SET NULL"),
    )

    # ---- catalogues
    op.create_table(
        "catalogues",
        _id(),
        _created_at(),
        _updated_at(),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("original_filename", sa.String(255), nullable=False),
        sa.Column("storage_key", sa.String(512), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        _enum("status", "UPLOADED"),
        sa.Column(
            "processing_progress", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("current_stage", sa.String(64), nullable=True),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=True),
        _pk("catalogues"),
        _fk("catalogues", "supplier_id", "suppliers", ondelete="RESTRICT"),
        _fk("catalogues", "uploaded_by_id", "users", ondelete="SET NULL"),
        _ck("catalogues", "progress_range", "processing_progress BETWEEN 0 AND 100"),
    )
    _idx("catalogues", "supplier_id")
    _idx("catalogues", "sha256")
    _idx("catalogues", "status")

    # ---- catalogue_pages
    op.create_table(
        "catalogue_pages",
        _id(),
        _created_at(),
        _updated_at(),
        sa.Column("catalogue_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        _enum("status", "PENDING"),
        _enum("page_type", nullable=True),
        sa.Column("page_type_confidence", sa.Float(), nullable=True),
        sa.Column("image_key", sa.String(512), nullable=True),
        sa.Column("thumbnail_key", sa.String(512), nullable=True),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("error_stage", sa.String(64), nullable=True),
        sa.Column("processing_error", sa.Text(), nullable=True),
        _pk("catalogue_pages"),
        _fk("catalogue_pages", "catalogue_id", "catalogues", ondelete="CASCADE"),
        _uq(
            "catalogue_pages",
            "catalogue_id",
            "page_number",
            name="uq_catalogue_pages_page_number",
        ),
        _ck("catalogue_pages", "page_number_positive", "page_number >= 1"),
    )

    # ---- source_images
    op.create_table(
        "source_images",
        _id(),
        _created_at(),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        _enum("kind"),
        sa.Column("storage_key", sa.String(512), nullable=False),
        sa.Column("width_px", sa.Integer(), nullable=False),
        sa.Column("height_px", sa.Integer(), nullable=False),
        *_bbox(nullable=True),
        sa.Column("region_confidence", sa.Float(), nullable=True),
        sa.Column("sha256", sa.String(64), nullable=True),
        sa.Column("phash", sa.String(16), nullable=True),
        _pk("source_images"),
        _fk("source_images", "page_id", "catalogue_pages", ondelete="CASCADE"),
    )
    _idx("source_images", "page_id")
    _idx("source_images", "phash")

    # ---- ocr_results
    op.create_table(
        "ocr_results",
        _id(),
        _created_at(),
        *_bbox(nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("line_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("language", sa.String(16), nullable=True),
        sa.Column("polygon", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("engine", sa.String(64), nullable=False),
        sa.Column("engine_version", sa.String(64), nullable=True),
        _pk("ocr_results"),
        _fk("ocr_results", "page_id", "catalogue_pages", ondelete="CASCADE"),
    )
    _idx("ocr_results", "page_id")

    # ---- detected_objects
    op.create_table(
        "detected_objects",
        _id(),
        _created_at(),
        *_bbox(nullable=False),
        sa.Column("source_image_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(128), nullable=False),
        sa.Column("prompt", sa.String(255), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("model_name", sa.String(128), nullable=False),
        sa.Column("model_version", sa.String(64), nullable=True),
        _pk("detected_objects"),
        _fk("detected_objects", "source_image_id", "source_images", ondelete="CASCADE"),
    )
    _idx("detected_objects", "source_image_id")

    # ---- segmentation_results
    op.create_table(
        "segmentation_results",
        _id(),
        _created_at(),
        sa.Column("detected_object_id", sa.Uuid(), nullable=False),
        _enum("status"),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("mask_key", sa.String(512), nullable=True),
        sa.Column("crop_key", sa.String(512), nullable=True),
        sa.Column("cutout_key", sa.String(512), nullable=True),
        sa.Column("white_bg_key", sa.String(512), nullable=True),
        sa.Column("thumbnail_key", sa.String(512), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("model_name", sa.String(128), nullable=False),
        sa.Column("model_version", sa.String(64), nullable=True),
        _pk("segmentation_results"),
        _fk("segmentation_results", "detected_object_id", "detected_objects", ondelete="CASCADE"),
        _uq("segmentation_results", "detected_object_id"),
    )

    # ---- image_embeddings
    op.create_table(
        "image_embeddings",
        _id(),
        _created_at(),
        sa.Column("source_image_id", sa.Uuid(), nullable=False),
        sa.Column("detected_object_id", sa.Uuid(), nullable=True),
        sa.Column("model_name", sa.String(128), nullable=False),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=False),
        _pk("image_embeddings"),
        _fk("image_embeddings", "source_image_id", "source_images", ondelete="CASCADE"),
        _fk("image_embeddings", "detected_object_id", "detected_objects", ondelete="CASCADE"),
    )
    _idx("image_embeddings", "source_image_id")
    _idx("image_embeddings", "detected_object_id")

    # ---- product_candidates
    confidence_columns = (
        "detection_confidence",
        "segmentation_confidence",
        "ocr_confidence",
        "association_confidence",
        "metadata_confidence",
        "overall_confidence",
    )
    op.create_table(
        "product_candidates",
        _id(),
        _created_at(),
        _updated_at(),
        sa.Column("catalogue_id", sa.Uuid(), nullable=False),
        _enum("status", "NEEDS_REVIEW"),
        _enum("origin", "AI"),
        _json("fields", "{}"),
        _json("flags", "[]"),
        _json("reasoning", "[]"),
        *[sa.Column(name, sa.Float(), nullable=True) for name in confidence_columns],
        sa.Column("merged_into_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        _pk("product_candidates"),
        _fk("product_candidates", "catalogue_id", "catalogues", ondelete="CASCADE"),
        _fk("product_candidates", "merged_into_id", "product_candidates", ondelete="SET NULL"),
        _fk("product_candidates", "reviewed_by_id", "users", ondelete="SET NULL"),
        *[
            _ck("product_candidates", f"{name}_range", f"{name} IS NULL OR {name} BETWEEN 0 AND 1")
            for name in confidence_columns
        ],
    )
    _idx(
        "product_candidates",
        "catalogue_id",
        "status",
        name="ix_product_candidates_catalogue_status",
    )

    # ---- candidate association tables
    for table, other_column, other_table in (
        ("candidate_pages", "page_id", "catalogue_pages"),
        ("candidate_images", "source_image_id", "source_images"),
        ("candidate_objects", "detected_object_id", "detected_objects"),
    ):
        op.create_table(
            table,
            sa.Column("candidate_id", sa.Uuid(), nullable=False),
            sa.Column(other_column, sa.Uuid(), nullable=False),
            sa.PrimaryKeyConstraint("candidate_id", other_column, name=op.f(f"pk_{table}")),
            _fk(table, "candidate_id", "product_candidates", ondelete="CASCADE"),
            _fk(table, other_column, other_table, ondelete="CASCADE"),
        )
        _idx(table, other_column)

    # ---- products
    op.create_table(
        "products",
        _id(),
        _created_at(),
        _updated_at(),
        sa.Column("slug", sa.String(255), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("sku", sa.String(128), nullable=True),
        sa.Column("model", sa.String(128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("material", sa.String(255), nullable=True),
        sa.Column("colour", sa.String(128), nullable=True),
        sa.Column("product_type", sa.String(64), nullable=True),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        _json("specifications", "{}"),
        sa.Column("price", sa.Numeric(12, 2), nullable=True),
        sa.Column("currency", sa.String(3), nullable=True),
        _enum("status", "DRAFT"),
        sa.Column("is_featured", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        _enum("origin", "HUMAN"),
        _json("field_provenance", "{}"),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_id", sa.Uuid(), nullable=True),
        sa.Column("catalogue_id", sa.Uuid(), nullable=True),
        sa.Column("source_page_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        _pk("products"),
        _fk("products", "category_id", "categories", ondelete="RESTRICT"),
        _fk("products", "supplier_id", "suppliers", ondelete="RESTRICT"),
        _fk("products", "candidate_id", "product_candidates", ondelete="SET NULL"),
        _fk("products", "catalogue_id", "catalogues", ondelete="SET NULL"),
        _fk("products", "source_page_id", "catalogue_pages", ondelete="SET NULL"),
        _fk("products", "created_by_id", "users", ondelete="SET NULL"),
        _uq("products", "slug"),
        _ck("products", "price_non_negative", "price IS NULL OR price >= 0"),
        _ck("products", "price_requires_currency", "price IS NULL OR currency IS NOT NULL"),
    )
    for column in ("sku", "status", "category_id", "supplier_id", "candidate_id", "catalogue_id"):
        _idx("products", column)

    # ---- product_images
    op.create_table(
        "product_images",
        _id(),
        _created_at(),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        _enum("image_type"),
        sa.Column("storage_key", sa.String(512), nullable=False),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("alt_text", sa.String(255), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("source_image_id", sa.Uuid(), nullable=True),
        sa.Column("detected_object_id", sa.Uuid(), nullable=True),
        sa.Column("segmentation_result_id", sa.Uuid(), nullable=True),
        _pk("product_images"),
        _fk("product_images", "product_id", "products", ondelete="CASCADE"),
        _fk("product_images", "source_image_id", "source_images", ondelete="SET NULL"),
        _fk("product_images", "detected_object_id", "detected_objects", ondelete="SET NULL"),
        _fk(
            "product_images",
            "segmentation_result_id",
            "segmentation_results",
            ondelete="SET NULL",
        ),
    )
    _idx("product_images", "product_id")

    # ---- processing_jobs
    op.create_table(
        "processing_jobs",
        _id(),
        _created_at(),
        _updated_at(),
        sa.Column("catalogue_id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_id", sa.Uuid(), nullable=True),
        _enum("job_type"),
        _enum("status", "QUEUED"),
        sa.Column("celery_task_id", sa.String(64), nullable=True),
        sa.Column("current_stage", sa.String(64), nullable=True),
        sa.Column("progress", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("pages_processed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_pages", sa.Integer(), nullable=True),
        sa.Column("products_found", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        _pk("processing_jobs"),
        _fk("processing_jobs", "catalogue_id", "catalogues", ondelete="CASCADE"),
        _fk("processing_jobs", "page_id", "catalogue_pages", ondelete="CASCADE"),
        _fk("processing_jobs", "candidate_id", "product_candidates", ondelete="SET NULL"),
        _fk("processing_jobs", "created_by_id", "users", ondelete="SET NULL"),
        _ck("processing_jobs", "progress_range", "progress BETWEEN 0 AND 100"),
    )
    _idx("processing_jobs", "catalogue_id")
    _idx("processing_jobs", "status")

    # ---- duplicate_flags
    op.create_table(
        "duplicate_flags",
        _id(),
        _created_at(),
        _updated_at(),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("existing_product_id", sa.Uuid(), nullable=True),
        sa.Column("other_candidate_id", sa.Uuid(), nullable=True),
        _enum("signal"),
        sa.Column("score", sa.Float(), nullable=False),
        _enum("status", "OPEN"),
        _json("details", "{}"),
        sa.Column("resolved_by_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        _pk("duplicate_flags"),
        _fk("duplicate_flags", "candidate_id", "product_candidates", ondelete="CASCADE"),
        _fk("duplicate_flags", "existing_product_id", "products", ondelete="CASCADE"),
        _fk("duplicate_flags", "other_candidate_id", "product_candidates", ondelete="CASCADE"),
        _fk("duplicate_flags", "resolved_by_id", "users", ondelete="SET NULL"),
        _ck(
            "duplicate_flags",
            "exactly_one_target",
            "num_nonnulls(existing_product_id, other_candidate_id) = 1",
        ),
    )
    _idx("duplicate_flags", "candidate_id")
    _idx("duplicate_flags", "existing_product_id")
    _idx("duplicate_flags", "status")

    # ---- enquiries
    op.create_table(
        "enquiries",
        _id(),
        _created_at(),
        _updated_at(),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("phone", sa.String(64), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        _enum("status", "NEW"),
        _pk("enquiries"),
        _fk("enquiries", "user_id", "users", ondelete="SET NULL"),
        _fk("enquiries", "product_id", "products", ondelete="SET NULL"),
    )
    _idx("enquiries", "user_id")
    _idx("enquiries", "product_id")
    _idx("enquiries", "status")

    # ---- wishlist_items
    op.create_table(
        "wishlist_items",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        _created_at(),
        sa.PrimaryKeyConstraint("user_id", "product_id", name=op.f("pk_wishlist_items")),
        _fk("wishlist_items", "user_id", "users", ondelete="CASCADE"),
        _fk("wishlist_items", "product_id", "products", ondelete="CASCADE"),
    )
    _idx("wishlist_items", "product_id")

    # ---- audit_logs
    op.create_table(
        "audit_logs",
        _id(),
        _created_at(),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_email", sa.String(320), nullable=True),
        _enum("action"),
        sa.Column("entity_type", sa.String(64), nullable=True),
        sa.Column("entity_id", sa.String(64), nullable=True),
        _json("details", "{}"),
        sa.Column("ip_address", sa.String(45), nullable=True),
        _pk("audit_logs"),
        _fk("audit_logs", "actor_id", "users", ondelete="SET NULL"),
    )
    _idx("audit_logs", "actor_id")
    _idx("audit_logs", "entity_type", "entity_id", name="ix_audit_logs_entity")
    _idx("audit_logs", "created_at")

    # ---- correction_records
    op.create_table(
        "correction_records",
        _id(),
        _created_at(),
        sa.Column("candidate_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        _enum("correction_type"),
        sa.Column("field_name", sa.String(128), nullable=True),
        sa.Column("ai_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("human_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        _json("context", "{}"),
        sa.Column("corrected_by_id", sa.Uuid(), nullable=True),
        _pk("correction_records"),
        _fk("correction_records", "candidate_id", "product_candidates", ondelete="SET NULL"),
        _fk("correction_records", "product_id", "products", ondelete="SET NULL"),
        _fk("correction_records", "corrected_by_id", "users", ondelete="SET NULL"),
    )
    _idx("correction_records", "candidate_id")
    _idx("correction_records", "product_id")


# --------------------------------------------------------------------------- downgrade
def downgrade() -> None:
    # Reverse dependency order. Extensions are left installed on purpose: other
    # databases/schemas on the server may rely on them.
    for table in (
        "correction_records",
        "audit_logs",
        "wishlist_items",
        "enquiries",
        "duplicate_flags",
        "processing_jobs",
        "product_images",
        "products",
        "candidate_objects",
        "candidate_images",
        "candidate_pages",
        "product_candidates",
        "image_embeddings",
        "segmentation_results",
        "detected_objects",
        "ocr_results",
        "source_images",
        "catalogue_pages",
        "catalogues",
        "app_settings",
        "categories",
        "suppliers",
        "users",
    ):
        op.drop_table(table)
